### ISSUE TITLE
Unable to understand the working.

### ISSUE THREAD

**Issue by rishissahu** [JonathanLaureano/TryColors#1]
Hello,

My name is Rishi and I came across your project on GitHub. I was interested in learning more about how it works and I had a few questions about the code.

Specifically, I was wondering how color mixing works and whether it's possible to modify it.

I appreciate the time and effort you've put into this project and any help you can provide would be greatly appreciated.

Thank you,
Rishi Sahu.

**Comment by JonathanLaureano** [comment]
on the mixing.js page there is a function that takes each hex color in the
array converts them to rgb values averages each value, combines them again
into one color and then displays that color.
you can fork or modify or whatever you want to it, I don't mind

**Comment by rishissahu** [comment]
Thank you for your prompt response and for explaining how color mixing works in your project. Your explanation has helped me understand the underlying mechanism.
